import './globals.css'
import { Inter } from 'next/font/google'
// import Navbar from '@/components/Navbar'  <-- ❌ Comment this out

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Pizza AI',
  description: 'Delicious pizzas generated by AI!',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar />  <-- Remove or comment this if Navbar component is missing */}
        {children}
      </body>
    </html>
  )
}
